<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LoanPlatform.Contracts.Domain\LoanPlatform.Contracts.Domain.csproj" />
    <ProjectReference Include="..\..\src\LoanPlatform.Contracts.Application\LoanPlatform.Contracts.Application.csproj" />
    <ProjectReference Include="..\..\src\LoanPlatform.Contracts.Infrastructure\LoanPlatform.Contracts.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\LoanPlatform.Contracts.Cli\LoanPlatform.Contracts.Cli.csproj" />
  </ItemGroup>

</Project>
